### PR TITLE
Added fuzzy filter.

### PR DESCRIPTION
**Pull request by anacarolinats**
This pull request adds  ''fuzzy'' filter to SearchQuerySet, allowing use fuzzy query in the backends.
It works like "startswith" but instead of "*" it adds "~" after each term in the query.

### CODE REVIEW

**Comment by matthewwithanm** [comment]
Any chance of this being revived now that #951 is closed?

**Comment by DASAR** [comment]
Any chance to get it done soon?

**Comment by acdha** [comment]
If someone wants to help this along, rebasing it against the current master branch and ensuring that all of the tests makes the review process much easier.

**Comment by anacarolinats** [comment]
@acdha This pull request was fixed here in #1211

**Comment by acdha** [comment]
This just merged

**Pull request closed without merging**
