### PR TITLE
Added logic to implement Interval Faceting (Solr only).

### PR DESCRIPTION
**Pull request by stmos**
This currently only works with Solr backend (>4.10).

More details about interval faceting can be found at: [Solr - Interval Faceting](https://cwiki.apache.org/confluence/display/solr/Faceting#Faceting-IntervalFaceting)

Example:
`intervals = ['[0,100]', '(100, *]']`
`sqs = SearchQuerySet()`
`sqs.interval_facet('price', intervals=intervals)`

Key replacement is supported as well:
` sqs.interval_facet('price', intervals=['{!key=cheap}[0, 100]', '{!key=expensive}[100, *)']).facet_counts()`

Output:
`{u'dates': {},
 u'fields': {},
 u'intervals': {'price': {u'cheap': 4, u'expensive': 47}},
 u'queries': {}}`

Syntax is explained at the URL posted above.
There is no need to specify the "facet=true"  when defining the search index for the fields you want to use for interval faceting.

Only requirement is that fields used for Interval Faceting must have “docValues” enabled (not required for Solr 5.20 and above)

### CODE REVIEW

**Comment by dwasyl** [comment]
Any idea if this PR would work with Solr 6.6 and being refactored into the current version of `haystack`?

**Comment by acdha** [comment]
It'd definitely need to be rebased against master since a bit has changed in the last 3 years

**Comment by dwasyl** [comment]
@acdha Thanks, makes sense. I rebased it again 2.8.1 while I move some apps over to Python 3. Once I have everything migrated over I'll rebase it against master and make a new PR for you.

Would you be okay merging in a rebased version of this? It's pretty straight forward, although backend specific.

**Comment by acdha** [comment]
Yes — if the tests are passing, I'll merge it.

**Comment by dwasyl** [comment]
Thanks @acdha, since I needed to rebase and update my local copy I turned it into a new PR #1934 to replace this original one.

**Pull request closed without merging**
