### PR TITLE
date_facet on Solr 6.6+

### PR DESCRIPTION
**Pull request by fabiopiovam**
# Using date_facet on Solr 6.6+

## changes
* fixed backend
* add attribute `date_facet_fields` on generic_views receiving a list of date_facet kwargs

## configuration
* Operating system version: Debian 9.11 and Ubuntu 18.04
* Search engine version: Solr 6.6.6
* Python version: 3.5
* Django version: 2.1
* Haystack version: 2.8.1

### CODE REVIEW

**Review by acdha — DISMISSED** [review]

**Comment by laborautonomo** [comment]
Hi, @acdha 
Thanks for review!

Disregard the last review request because I unintentionally requested.

best regards,
Fábio Piovam

**Comment by asedeno** [comment]
Is it possible to have pysolr report back on what version of solr it is talking to? If so, this can be transparent to the user rather than requiring configuration changes.

**Comment by ingloriousp** [comment]
Can someone merge this pull request?

**Comment by fabiopiovam** [comment]
Hi, @acdha 

I updated the AUTHORS file in favor of merge. Do I have something else to fit in?

**Review by acdha — APPROVED** [review]

**Pull request merged**
