### PR TITLE
Basic Whoosh facet support

### PR DESCRIPTION
**Pull request by hellmanj**
resubmitting for @audax (original PR #914)  I didn't do anything except rebase to master

### CODE REVIEW

**Comment by audax** [comment]
Thank you, I am a bad lazy person.

**Comment by auvipy** [comment]
probably need another re base

**Comment by hellmanj** [comment]
Done, thanks for the prompt.

**Comment by valentijnscholten** [comment]
So after 3 PRs, this the end of facet support for whoosh?

**Pull request closed without merging**
