### PR TITLE
Add model filter to SearchQuerySet for ES5.

### PR DESCRIPTION
**Pull request by JClubb3**
Fixes issue #1622.

### CODE REVIEW

**Comment by Mibou** [comment]
I don't know why this commit is breaking the tests but it definitely fixes the bug on my side.

**Comment by RandomJo** [comment]
> I don't know why this commit is breaking the tests but it definitely fixes the bug on my side.

Same for me!

**Comment by sollerd** [comment]
I also can confirm that this commit is fixing the problem. Is there any chance that we can get this merged?

**Comment by sk1p** [comment]
> I don't know why this commit is breaking the tests but it definitely fixes the bug on my side.

This is because the default query behavior is now different: `HAYSTACK_LIMIT_TO_REGISTERED_MODELS=True` means there are now two filters applied in the failing test case: the `"geo_distance"` key is ANDed with a second filter `{"terms": {"django_ct": [...]}}`. See https://github.com/sk1p/django-haystack/commit/98cbad47063d562957d64925a49db9e4d37ee594 for a proposed fix, including a new test case that asserts the new behavior of `build_search_kwargs`

**Comment by Lucianovici** [comment]
Hi there, I recently found this bug as well. Can we merge @JClubb3 's fix? Can someone please review this?
Thanks.

**Comment by acdha** [comment]
Can you help fix the tests? Haystack could use a contributor who uses ElasticSearch.

**Comment by Lucianovici** [comment]
I'll attempt to fix the tests but next month. (tight deadlines for me right now).
However, as a workaround - I just stored a new field `facility_type` in my index, this way I can transform this:

```
In [66]: SearchQuerySet().filter(name_auto='Sen').models(Floor).count()
Out[66]: 2
```

To something like this:

```
In [67]: SearchQuerySet().filter(name_auto='Sen').filter(facility_type='floor').count()
Out[67]: 0
```

**Comment by sk1p** [comment]
> Can you help fix the tests? Haystack could use a contributor who uses ElasticSearch.

I started to develop a fix for the tests a while ago - feel free to take this and/or build upon it:

https://github.com/sk1p/django-haystack/commit/2f3b90b1c786eabac4c058fce6bd04b9d3fb89f0

**Comment by daxaxelrod** [comment]
No updates i assume?

**Comment by jonesnc** [comment]
I'm also running into this issue: `models()` is not working so my `SearchQuerySet` just includes everything in the `index`, regardless of whether or not the doc has the `django_ct` I passed to `models()`.

Are there any updates on this issue?

**Comment by puzzlet** [comment]
I accidentally PR'ed a duplicate at #1788 which is merged.

**Pull request closed without merging**
