### PR TITLE
[WIP] Use standard Django test runner

### PR DESCRIPTION
**Pull request by acdha**
This is a follow to finish #1834 — I got overeager seeing the “WIP” cleared.

TODO:

* [ ] Remove wait-for-solr script from the other matrix builds
* [ ] Consider adding matrix for other Solr versions (6 is rather old by now)

### CODE REVIEW

**Comment by claudep** [comment]
Do you intend to do the remaining bits yourself, or do you expect me to contribute also? If you have a clear idea of what's missing, I'd appreciate your final touch :-)

**Comment by acdha** [comment]
I'll take a stab at it over the weekend.

**Review by cclauss — APPROVED** [review]
LGTM

**Comment by claudep** [comment]
@acdha, @cclauss, Should we push this PR in its current state? Or are TODOs mandatory to go ahead? Unless something is done soon, the project should then be declared as dead.

**Comment by cclauss** [comment]
My sense is that this is ready to land as is.

**Comment by acdha** [comment]
@claudep I think you're right that we should merge it. Longer term, Haystack could really use new maintainers. I decommissioned the project I primarily used it on a couple of years ago and my spare time is pretty limited these days. I've been thinking about discussing it with Jazzband to see if we could turn everything in this organization over. If you have any advice, I'd be interested in your opinion.

**Comment by cclauss** [comment]
Your reviews please on #1855

**Comment by claudep** [comment]
Moving to Jazzband could be a good thing, but this will not automagically add new maintainers. I'd suggest opening a ticket to collect any interested future maintainers, and then the new team, if any, could help to move to Jazzband.

**Pull request merged**
