### PR TITLE
Highlight elasticsearch 2.X is not supported yet

### PR DESCRIPTION
**Pull request by martinsvoboda**
I spend several hours with problems with elasticsearch 2

### CODE REVIEW

**Comment by sampeka** [comment]
Good catch :+1:  there's also a reference to the compatible versions of elasticsearch in `docs/installing_search_engines.rst`. If you could fix that as well I'll merge it in

**Comment by martinsvoboda** [comment]
Done, it is ready for merge.

**Comment by sampeka** [comment]
Thanks, final thing - can you squash the commits? Better to keep the commit history as clean as possible.

http://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

**Comment by martinsvoboda** [comment]
Sound reasonable. Done.

**Pull request merged**
