### PR TITLE
Port of fuzzy searching from anacarolinats fork

### PR DESCRIPTION
**Pull request by sbussetti**
Refs: #937

This patch from @anacarolinats works great and implements a feature I very much need.  
This pull request is simply her branch, minus some formatting changes and out of date items that were affecting the merge-ability.

The patch was submitted over a year ago and I haven't seen any activity from the original author so, here it is.

All tests pass for me locally.

### CODE REVIEW

**Comment by anacarolinats** [comment]
@sbussetti Thanks for fix out of date items. Hope it can be merged!

**Comment by SalahAdDin** [comment]
:+1:  thank you.

**Comment by sbussetti** [comment]
worth noting that the travis build failures are due to some kind of issue downloading Solr during the test env setup.

**Comment by WimCrols** [comment]
When is this going in, please?

**Comment by acdha** [comment]
Just merged

**Pull request closed without merging**
