### PR TITLE
flake8

### PR DESCRIPTION
**Pull request by dulmandakh**
Introduce flake8 check, and fix issues.

### CODE REVIEW

**Comment by acdha** [comment]
Might be worth adding a few other flake8 plugins — I had enabled these on pysolr:

https://github.com/django-haystack/pysolr/blob/master/.pre-commit-config.yaml#L36-L39

These days I'd probably use this list:

```
                - flake8-assertive
                - flake8-builtins
                - flake8-comprehensions
                - flake8-logging-format
                - flake8-eradicate
                - flake8-bugbear
```

Might also be good to add isort and black while we're at it since we [tell people we're using those](https://github.com/django-haystack/django-haystack/blob/master/docs/contributing.rst#guidelines-for-contributing-code) and IIRC there's a GitHub action which can automatically apply the changes now.

**Comment by dulmandakh** [comment]
@acdha I'm preparing another PR for black+isort because I didn't expected that you would ask them

**Comment by dulmandakh** [comment]
@acdha also I didn't have time to fix all the issues from various plugins, so I added just flake8 to see if you would accept the change.

**Comment by dulmandakh** [comment]
also run flake8 on tests, and there are so many issues to fix

**Comment by acdha** [comment]
> also run flake8 on tests, and there are so many issues to fix

I think it'd make sense to ignore tests initially.

**Comment by acdha** [comment]
Looking at this, I'm thinking we defer the logging format updates since those are ~50 separate errors.

**Comment by dulmandakh** [comment]
@acdha let's merge this as is. I'll try to add flake8 plugins and fix issues.

**Comment by acdha** [comment]
> @acdha let's merge this as is. I'll try to add flake8 plugins and fix issues.

Thanks - my first thought is that we should get Black + isort setup and then I'd probably want to review the current crop of flake8 warnings. There are a few general cleanups to be made but I've certainly seen worse. I only see one case of old Python2-isms (haystack/panels.py:43:59 has a dict iter* call) but otherwise it looks pretty straight forward.

**Pull request merged**
