### PR TITLE
To fix the bug in contains input type and to add endswith input type to backends

### PR DESCRIPTION
**Pull request by antonyr**
- This code is backward compatible.
- This commit adds ability to use `endswith` input type with backends. Following code
```python
SearchQuerySet().filter(name__endswith='parker')
```
will generate `q=name:*parker`
- This commit fixes contains bug. In order to use `contains` against Solr, Elastic search or Whoosh, following code
```python
SearchQuerySet().filter(name__contains='james')
```
should generate `q=name:*james*` in the query parameter.
- This also fixes the failing tests in the master branch.

### CODE REVIEW

**Comment by antonyr** [comment]
This PR address the following issues too.
#1286
#1259 
#1216 
#1041

**Comment by sampeka** [comment]
Are you able to resolve the merge conflicts? Aside from that, this looks good to me - has new test coverage and making the default filter `__content`  means that `__contains` behaves more intuitively. Seems in line with the acdha's proposal for handling `__contains` here: https://github.com/django-haystack/django-haystack/issues/1041#issuecomment-149902911

Only issue is whether the changes to `__contains` are going to be a problem for people updating. Presumably since it was the default filter before it shouldn't be, but it is still a change to the core api... Thoughts @acdha ?

**Comment by aamirtharaj-rpx** [comment]
@sampeka I resolved the merge conflicts and get the tests passing too.
The changes to `__contains` is a problem as this will return more results than what it has been giving. However this is a necessary upgrade step for them.

Please let me know your thoughts.

**Comment by sebslomski** [comment]
@acdha @sampeka @aamirtharaj-rpx 
The current state of the elasticsearch implementation with contains is broken - it's not raising an error but just does not what is expected.
This commit fixes this problem very well - also all tests are passing.
Is there anything stopping from merging this pr (except the merge conflict)?

I'm happy to assist and work on a solution with you to fix this problem, but right now it's just broken.

**Comment by antonyr** [comment]
@sebslomski @acdha @sampeka 
I have resolved the merge conflicts. Please review this PR and merge it.

**Comment by sebslomski** [comment]
Works perfectly on my machine, please merge @acdha.

**Comment by SalahAdDin** [comment]
@acdha Plase!

**Comment by korbinianfritsch** [comment]
+1, works fine - please merge this PR

**Comment by gregmuellegger** [comment]
I have debugged this issue a couple of times now why ``contains`` didn't work as expected, and always find myself googling until I remember that it's a known bug.

Having this merged would be wonderful and saves a lot of undirected debugging for a known issue.

@acdha are there any objectives open before this can be merged?

**Comment by gregmuellegger** [comment]
Awesome! Thanks for taking the effort to review and merge. I really appreciate it!

**Pull request merged**
