### PR TITLE
Backend for Elasticsearch 2.x

### PR DESCRIPTION
**Pull request by ElSaico**
This continues where #1391 left off, rebasing and fixing expected behaviors of recent versions of Haystack.

### CODE REVIEW

**Comment by seocam** [comment]
@acdha we have been using this backend since March and in production since June. If you need any info or any tests you would like us to perform just let us know.

Today @ElSaico we'll start to code the backend for ES 5 as well.

**Comment by acdha** [comment]
@seocam Sorry for not responding earlier – I'm looking to merge this this week & will get back to you as soon as I switch over to working on Haystack again.

**Comment by SalahAdDin** [comment]
@acdha Thank you!

**Comment by acdha** [comment]
I'm working on a few minor changes as part of the merge process here:

https://github.com/acdha/django-haystack/tree/es2-branch-merge

**Comment by acdha** [comment]
I just uploaded v2.6.0 to PyPI:

https://django-haystack.readthedocs.io/en/v2.6.0/changelog.html#v2-6-0-2017-01-02 
https://pypi.python.org/pypi/django-haystack/2.6.0

**Pull request merged**
