### PR TITLE
forms.py: Fix Django 4.0 compatibility

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/django-haystack/django-haystack/issues/1826

### CODE REVIEW

**Comment by jayvdb** [comment]
Failing job needs restarting

**Comment by ajslater** [comment]
I believe this PR is missing a required change for Django 4.0 compatibility:

### This change is required
```diff
haystack/admin.py:7
< from django.utils.translation import ungettext
---
> from django.utils.translation import ngettext
119c119
<         selection_note = ungettext(
---
>         selection_note = ngettext(
124c124
<         selection_note_all = ungettext(
---
>         selection_note_all = ngettext(
```

### These two changes are optional, but will remove deprecation warnings

```diff
haystack/backends/whoosh_backend.py
10c10
< from django.utils.datetime_safe import date, datetime
---
> from datetime import date, datetime
```
```diff
haystack/fields.py
5c5
< from django.utils import datetime_safe
---
> from datetime import date, datetime 
398c398
<                 return datetime_safe.date(
---
>                 return date(
431c431
<                 return datetime_safe.datetime(
---
>                 return datetime(
```

**Comment by ajslater** [comment]
Also in tox.ini I think you left out including py39 on this line:

https://github.com/django-haystack/django-haystack/pull/1828/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449L5

**Comment by jayvdb** [comment]
The admin.py change already occurred in https://github.com/django-haystack/django-haystack/commit/a1eabc0337bb91890042b779c0314853f6fad54b

**Review by claudep — APPROVED** [review]
Looks good!

**Review by acdha — APPROVED** [review]
We might want to drop Python 3.6 (which hit end of life in December) and add 3.10 but that's probably best as another pull-request.

**Pull request merged**
