### PR TITLE
Highlighting now works for exact searches (the ones with quotes)

### PR DESCRIPTION
**Pull request by kevinrenskers**
Added a simple replace('"', ''), so that highlighting now works when you search with quotes, like "hello world" instead of hello world.

### CODE REVIEW

**Comment by SteveByerly** [comment]
thanks for the PR @kevinrenskers  i'm sorry you never received any feedback on this. 

i'll be trying to incorporate the exact query highlighting soon, but i think it should highlight the phrase exactly, instead of breaking up each word and highlighting separeately.

**Comment by kopf** [comment]
Hey, I just happened to run into this problem too.

@SteveByerly: Any chance you could give me an approximate estimate as to how soon "soon" might be? :) If time is tight at the moment, and you have an idea of how this should be implemented, please just let me know, and I could take care of any heavy lifting for you. Thanks!

**Comment by SteveByerly** [comment]
@kopf I'm hoping to get it merged into master by this weekend. If you need it sooner, it's actually really easy to override the default highlighter. Just create a new class that inherits `haystack.utils.highlighting.Highlighter` and point the `HAYSTACK_CUSTOM_HIGHLIGHTER` setting to its dotted path.

**Comment by kopf** [comment]
@SteveByerly That's great news! If you remember, can you ping me a link to the PR once it's open - I'd just be curious to see what the implementation is like. I'm actually using a custom highlighter already, but would much rather hold out and have this fixed in haystack, rather than hacking a solution together myself on the application side.

**Comment by SteveByerly** [comment]
I'll try to remember. The PR i'm working on is currently #1402

**Pull request closed without merging**
