### PR TITLE
Basic Whoosh facet support

### PR DESCRIPTION
**Pull request by audax**
Only basic facets, no dates and query facets are supported.

This is an updated version of the pull request (#816) from @parruc
with updated tests and documentation.

### CODE REVIEW

**Comment by avoine** [comment]
Thank you for this. I really hope it get merge someday.

**Comment by acdha** [comment]
@audax Can you rebase this against the current master? That should take care of the unrelated test failures and it'd be nice to get this into 2.4.0

**Comment by audax** [comment]
I can do it in about 2 weeks if thats ok, I am currently in my exam period.

**Comment by audax** [comment]
I won't update this PR anymore since I don't even use the software anymore. Hopefully the code will still be useful.

@sgaist Feel free to resubmit the changes in your own PR.

**Pull request closed without merging**
