### PR TITLE
Moved signal processor loading to app_config.ready

### LINKED ISSUE #1212: Allow HAYSTACK_SIGNAL_PROCESSOR Class to Import Models
Currently, if you use the `HAYSTACK_SIGNAL_PROCESSOR` function to set to a class which imports a model, then you can get ciruclar imports. This was also reported here:
http://stackoverflow.com/questions/17049426/importerror-when-using-haystack-2-0-0-with-django-1-5-and-gunicorn-wsgi

I am not sure what is causing this, but it would be nice if our signal processors could import our models.

### PR DESCRIPTION
**Pull request by claudep**
Fixes #1212.

### CODE REVIEW

**Comment by claudep** [comment]
As expected, this fails on Django 1.6. Is 1.6 supposed to be supported after the 2.4 release or not?

**Comment by acdha** [comment]
@claudep I'm leaning no unless someone has a really compelling reason (i.e. they're willing to step up and support it). The core Django team dropped support for 1.6 in April and I see no reason to support it longer than they do: https://www.djangoproject.com/download/

**Comment by claudep** [comment]
Dropping 1.6 is tracked in #1190. I guess most of the work is on the documentation side.

**Comment by acdha** [comment]
Likely, yes, although it might be a good time to review the various conditional imports & wrapper functions. If memory serves, a bunch of those are moot once we only support Django 1.7+.

**Comment by claudep** [comment]
Rebased on current master.

**Pull request closed without merging**
