### PR TITLE
Use external six. Add tests for Django 3.0.

### PR DESCRIPTION
**Pull request by GabrielDumbrava**
# Hey, thanks for contributing to Haystack. Please review [the contributor guidelines](https://django-haystack.readthedocs.io/en/latest/contributing.html) and confirm that [the tests pass](https://django-haystack.readthedocs.io/en/latest/running_tests.html) with at least one search engine.

# Once your pull request has been submitted, the full test suite will be executed on https://travis-ci.org/django-haystack/django-haystack/pull_requests. Pull requests with passing tests are far more likely to be reviewed and merged.

### CODE REVIEW

**Comment by acdha** [comment]
Since we're touching this, I'd prefer to remove six entirely along with Python 2 support.

It would also be useful to update the issue description to be describe all of the changes.

**Comment by zfreeds** [comment]
@acdha , is there a current workaround for those using Haystack with the latest Django version?

**Comment by acdha** [comment]
@zfreeds If you have a requirement that you upgrade to the latest major release immediately, I'd suggest contributing to the work updating and testing this branch.

**Comment by Tuhib** [comment]
What is the update here, is there any progress?

**Comment by acdha** [comment]
See #1720. Please remember that this is a volunteer project so if you need something on a schedule your best bet is to help with development and testing.

**Comment by minusf** [comment]
hello. did this make it into any pypi release?  `2.8.1` is trying to use the non existent django one...

**Comment by acdha** [comment]
@minusf see the previous comment. It's been on PyPI since February but nobody who has asked about it has reported results from their testing.

**Comment by avrahamkam** [comment]
> hello. did this make it into any pypi release? `2.8.1` is trying to use the non existent django one...

Try pip install "git+https://github.com/django-haystack/django-haystack.git@08dd9471a0137ba87b8145cf1ec5ff9d8d498a2e"

**Pull request closed without merging**
