### PR TITLE
Fix code to enable highlighting

### PR DESCRIPTION
**Pull request by merwok**

### CODE REVIEW

**Comment by SteveByerly** [comment]
I think the comments are clear you're supposed to add your own code. I think the PR makes it a bit more confusing.

**Comment by merwok** [comment]
Would you accept the PR if I use ellipsis (`...`) instead of `pass`?  That would make the syntax valid and convey to readers that they need to fill in.

**Comment by SteveByerly** [comment]
sure

**Comment by merwok** [comment]
Changed!

**Pull request merged**
