### PR TITLE
Add official support for Django 1.10

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Seems not ready yet...

**Comment by claudep** [comment]
Reopening for a new series of tests.

**Comment by claudep** [comment]
Failing tests:
test_haystack.solr_tests.test_solr_backend.LiveSolrMoreLikeThisTestCase.test_more_like_this_defer
test_haystack.elasticsearch_tests.test_elasticsearch_backend.LiveElasticsearchMoreLikeThisTestCase.test_more_like_this

Deferred field management changed from https://github.com/django/django/commit/7f51876f99851fdc3fef63aecdfbcffa199c26b9
@acdha I guess those tests might need updating, but I'll not touch that myself. Feel free to take over this PR.

**Comment by acdha** [comment]
Tagged v2.5.1 – thanks again to @ellmetha

**Pull request closed without merging**
