### PR TITLE
Django 19 support

### PR DESCRIPTION
**Pull request by gustavi**
Django 1.9 support.

Based on #1277 (no news from the author) : 

> Remove django.conf.urls.patterns, since they already have been removed from the doc and will be removed in Django 2.0
> 
> This removes in Django 1.9 the warning:

> RemovedInDjango110Warning: django.conf.urls.patterns()
> is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of
> django.conf.urls.url() instances instead.
>   name='redactor_upload_file'),

> Also Updates the command update_index to match new arguments parser in Django

Fix : 

- #1282
- #1293
- #1291

### CODE REVIEW

**Comment by auvipy** [comment]
could you fix the build fails?

**Comment by gustavi** [comment]
I have no idea what is wrong.

**Comment by sk1p** [comment]
There were three different causes for the test failures:

1) Django 1.9 doesn't load initial_data fixture automatically any more
2) The admin URL for change views changed
3) Argument parsing is slightly broken (``type="string"`` vs ``type=str``, *args were used to read app labels, not the new ``options['app_labels']``, ...)

I fixed these problems and merged the master branch into my fork to resolve the above mentioned conflict.

@gustavi feel free to pull from https://github.com/sk1p/django-haystack/tree/django_19 to update your pull request

**Comment by acdha** [comment]
Sorry about the delays but as of 10bcc7668ccaab499f8db516fd59de182aadbcb4 the tests are passing on Django 1.9. If you have any remaining gaps please either rebase against master or close this & open a separate pull request.

**Comment by pembo13** [comment]
Just looking for any anticipated timeline for release of working django-haystack for Django 1.9

**Comment by acdha** [comment]
If you have time, https://pypi.python.org/pypi/django-haystack/2.5.dev1 is newly out:

https://django-haystack.readthedocs.io/en/latest/changelog.html

**Comment by acdha** [comment]
Closing this issue since 2.5.0 is out

**Pull request closed without merging**
