### PR TITLE
Adaptations for Solr 5.0.0

### PR DESCRIPTION
**Pull request by elishowk**
Solr 5.0.0 is easy to deploy with cloud Cores with automatic managed-schema and no more schem.xml.
Solr 5.0.0 can edit a core's configuration via with the Schema REST API. 
This is what this pull request does. Along with an updated documentation.

Refers to issue #1147 and try to resolve it...

### CODE REVIEW

**Comment by philippeluickx** [comment]
+1, need to try this out...

**Comment by elishowk** [comment]
I think I fixed the failed test (Python 3 compat). The merge should be faisable now. Thanks

**Comment by galuszkak** [comment]
@elishowk I think you need to rebase this PR.

**Comment by acdha** [comment]
Rebasing it would be much appreciated

**Comment by elishowk** [comment]
Rebased on the master and squashed my commit in one commit for this feature. Hope this will work for you.

**Comment by elishowk** [comment]
The tests fails only on one configuration while starting solr testing server on Travis-ci. Don't know what to do, this is not a test failure I can manage myself ...

**Comment by datakid** [comment]
I'd appreciate this getting merged/finalised soon.

**Comment by elishowk** [comment]
I would too, but I don't know what to do about the travis build, there's only one build that failed because the Solr erver wouldn't start (check 337 in https://travis-ci.org/django-haystack/django-haystack/builds/56762056). Anyway, the tests are OK on my part.

**Comment by galuszkak** [comment]
Can someone restart test? Sounds to me that this one time thing. It relates to solr not code. So maybe it only failed once in that py34-dj1.6 https://travis-ci.org/django-haystack/django-haystack/jobs/56762069 (337.10).

**Comment by noisy** [comment]
@acdha 
is it a chance to merge this in the near future?

**Comment by elishowk** [comment]
Hi, I've recently rebased tried to make the tests pass completely, but
there an issue with Solr 5 installation on the test server. If someone
is interested in making them pass, feel free!

--
  Elias
  elias@showk.me
 
 
 
Le Sam 01 août 2015, à 20:58, Krzysztof Szumny a écrit :
> @acdha[1]
> 
is it a chance to merge this in the near future?


> —
> Reply to this email directly or view it on GitHub[2]. 


>  
 


Links:

  1. https://github.com/acdha
  2. https://github.com/django-haystack/django-haystack/pull/1148#issuecomment-126945190

**Comment by elishowk** [comment]
I have updated the test suite to test for both Solr 4 and Solr 5. Everything is fine on Travis, except for a Python 3 and Pysolr related issue (PR still waiting https://github.com/toastdriven/pysolr/pull/162) at https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L445 when python 3 need a b'<?xml' to cast to bytes this answer (read https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal/6269785#6269785) 

Waiting for news from the maintainers from both pysolr and haystack.
But I think this may be the time when haystack can merge Solr 5+ support.

**Comment by vmarkovtsev** [comment]
I confirm that @elishowk's  version works with Solr 5.3. No schema.xml is needed. Great work, thanks!

**Comment by gnarea** [comment]
Hi! Since the bug on PySolr is now fixed and someone has confirmed that it all works, can this be merged now? If further testing is needed I'm happy to wait.

**Comment by DevHugo** [comment]
We love to have the support and the new release. Looking forward to hearing from main developers.

**Comment by ahoho** [comment]
This seems to work for me, but following changes in a `SearchIndex` subclass, `rebuild_solr_index` fails to update `managed-schema`.

Am I missing something on my end?

**Comment by mahajandiwakar** [comment]
Hi,

I am using haystack field 'edge_ngram' for auto-complete functionality. However, using build_solr_schema fails to add the field with 'edge_ngram' and the fieldtype is also missing from the managed-schema file. Am I missing anything here? Any pointers will be helpful.

Thanks

**Comment by elishowk** [comment]
In Solr 5+, the schema is managed by default via the admin API, not by xml file. Please read more here the [Read-me doc in the pull-request](https://github.com/Stupeflix/django-haystack/blob/0b24f35d1e6ce78e56165f172210c9324debc605/docs/installing_search_engines.rst#update-your-schema-from-the-indexes) or [Solr documentation here](https://cwiki.apache.org/confluence/display/solr/Managed+Schema+Definition+in+SolrConfig)

**Comment by DevHugo** [comment]
Your branch should be rebase ;).

**Comment by elishowk** [comment]
Yep, I will do, but please @acdha could you confirm me that it will be merged rather quickly ? If not, I will wait the owner's signal to work on it.

**Comment by acdha** [comment]
@elishowk Yes – if it's a clean branch with test coverage it won't take very long for me to merge & we should ship a release by then, too.

**Comment by elishowk** [comment]
After rights to access a team's repo, I've forked these commits to my account, and submitted a new PR here #1315 .

**Pull request closed without merging**
