### PR TITLE
Better default configs

### PR DESCRIPTION
**Pull request by RabidCicada**
Partial answer to #1520 and original symptoms reported in #1504.  This upgrades to:
Remove deprecated settings (as reported by solr itself).  Remove default operator and default text field.  Also removed two analysis modules that are deprecated and replaced with intended modules for upgrade path.
Added new request handlers as suggested (no new tests as of now -- but doesn't break existing)
Can you squash the commit history?...it's messy.

### CODE REVIEW

**Comment by RabidCicada** [comment]
Somethign happen to Travis?...all the elasticsearch stuff is failing

**Comment by acdha** [comment]
Looks like the ElasticSearch download site changed to be under https://artifacts.elastic.co/packages/ according to https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html#deb-repo. I'm not sure if that's as simple as replacing the old URL with https://artifacts.elastic.co/packages/1.7/apt

**Comment by acdha** [comment]
@RabidCicada ES on Travis is fixed in #1530 - rebasing this branch against master now should fix that.

**Comment by RabidCicada** [comment]
I probably did things all kinds of wrong.  I rebase my master against yours and rebased my feature branch off that.  Now all history is nice and clean...but I might have screwed someone who was watching my fork :(.  Sorry to anyone out there.

**Comment by RabidCicada** [comment]
knock knock:).  Also...thanks for shepherding django-haystack to begin with @acdha.  Saved me having to dive in too hard when first getting aboard the search train.

**Comment by RabidCicada** [comment]
@acdha Heyo.  There a chance to get this pulled in?  It's a march in the right direction for keeping the deprecated cruft out of our template.  And using the right analysis modules.

**Comment by acdha** [comment]
Sure, merged

**Pull request merged**
