### PR TITLE
make empty lists return null or default

### PR DESCRIPTION
**Pull request by janwin**
This fix resolves the issue with integerFields trying to convert empty list in case a Nnull value is returned from the datasource

Tests are passing

### CODE REVIEW

**Comment by Terr** [comment]
Thanks for fixing this. Would you mind if I write some extra tests for this case and open a PR towards your branch?

**Comment by janwin** [comment]
Sure, go on! I would appreciate it!

**Comment by Terr** [comment]
I have some difficulty in reproducing the issue. Am I correct that your setup looks like this:

```
class LeftModel(models.Model):
    some_foreign_key = models.ForeignKey('RightModel', null=True)

class RightModel(models.Model):
    some_integer_field = models.IntegerField()
```

And that your `model_attr` is referring to `some_foreign_key__some_integer_field` ?

**Comment by Terr** [comment]
I think I got it: the ForeignKey relation/column is defined in the 'right' model? I added a test for it [here](https://github.com/Terr/django-haystack/commit/45293cafbed0ef6aeb145ce55573eb32b1e4981f): it fails without your fix and passes with it. 

For some reason I don't see your fork when trying to create a PR, but if you want you can cherry pick the commit.

**Comment by janwin** [comment]
thanks @Terr i added your test to the PR

**Comment by thongly** [comment]
Is this awaiting further review, or tests?

**Comment by acdha** [comment]
@thongly It looks like the CI build was just due to the multiprocessing race condition. If you wanted to rebase this against the current master branch and confirm that the tests pass that'd be helpful

**Comment by acdha** [comment]
The tests just passed after a restart

**Comment by StevenFerreira** [comment]
I've just created a separate pull request minutes ago and all tests passed locally

**Comment by thongly** [comment]
@acdha - Are you planning on pushing a release soon too?  Wondering if we need to pip install the branch-specific version or whether we can wait on your official release.  Please advise if you have a ETA.

**Comment by acdha** [comment]
If you need it right now, I would use a pinned commit. I would like to get
a release fairly soon but didn't have a specific date in mind.

**Pull request merged**
